version: 2.1
jobs:
  tests:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - run:
          name: "Testing CLI"
          command: make test

workflows:
  tests:
    jobs:
      - tests
