version: 2.1
jobs:
  tests:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - run:
          name: "Testing CLI"
          command: make tests
  release:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - run: 
          name: "Running GoReleaser"
          command: curl -sfL https://goreleaser.com/static/run | bash

workflows:
  main:
    jobs:
      - tests
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
